---
name: Upgrade Dependencies
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.STUDIO_GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm install -g bob@4
      - run: bob updep
      - uses: cliffano/command-docker-action@v1.4.0
        with:
          image: cliffano/studio:2.11.1
          command: 'make ci'
      - uses: cliffano/save-changes-action@v1.0.0
        with:
          message: "Upgrade dependencies to latest"
          github_token: ${{ secrets.STUDIO_GITHUB_TOKEN }}
